### PR TITLE
String tests

### PR DESCRIPTION
**Pull request by jmeas**
@pete-the-pete did some great work adding string tests over in #66. In this PR, I'm going to do some final tidying up of the PR, then squash it down for merge.

### CODE REVIEW

**Comment by jmeas** [comment]
Mmk @ashleygwilliams / @kadamwhite / @pete-the-pete – I tidied up this PR, and I'd love for y'all to review it if you had time.

The last thing I want to do is squash the commits, but I figure I can do that right before merging.

**Comment by kadamwhite** [comment]
The tests look OK, but it needs to be updated to account for #112: the strings module uses the old require declaration, rather than the `exports.namespace = {}` strategy.

**Comment by ashleygwilliams** [comment]
this looks good to me @jmeas - if you squash i'll merge

**Comment by jmeas** [comment]
> this looks good to me @jmeas - if you squash i'll merge

...I think I somehow managed to miss this comment altogether. I'll update thiz

**Comment by jmeas** [comment]
Updated @ashleygwilliams

**Comment by ashleygwilliams** [comment]
awesome @jmeas! merging

**Comment by ashleygwilliams** [comment]
:ribbon:

**Comment by jmeas** [comment]
Thanks, @ashleygwilliams! now I just need to get together some solutions :)

**Pull request merged**
