### PR TITLE
Update flowControl.js

### PR DESCRIPTION
**Pull request by pertrai1**
The buzz and fizz where backwards for 3 and 5.

### CODE REVIEW

**Comment by rmurphey** [comment]
It sounds like this can be closed then?

**Comment by pertrai1** [comment]
Are the comments correct for this file?

**Comment by davecocoa** [comment]
The comments are correct but confusing in my opinion. Because the program exclusively uses `% x` for these purposes as `not divisible by x` but the comments make positive assertions about `divisible by x`, as a logical conclusion from early return statements. I think this could be made clearer by just adding a comment on line 20 reminding the reader `// divisible by at least one of 3 or 5, possibly both`, but it's really a matter of taste.

**Comment by rmurphey** [comment]
I'd be grateful for a PR that clears up the comments!

**Comment by davecocoa** [comment]
@pertrai1 could you take a look at my [proposed change](https://github.com/davecocoa/js-assessment-answers/blob/patch-1/app/flowControl.js) and let us know if it's any clearer?

**Comment by pertrai1** [comment]
@davecocoa Yes, that makes it much clearer for someone at my skill level to understand.

**Comment by ashleygwilliams** [comment]
closing. opening an issue to make a more "intuitive" fizzbuzz solution for a beginner (checking divisibility, i.e. ===0, not "indivisibility", which is harder to reason about.) 

@pertrai1 @davecocoa @hirechrismeyers please continue the conversation on that issue if you are interested. thanks!

**Comment by jmeas** [comment]
@ashleygwilliams summarized it well, but to be more explicit:

The comments are **correct** the way that they are. This PR changed this to be invalid.

We believe that this is caused by potentially confusing code [over here](https://github.com/rmurphey/js-assessment-answers/blob/master/app/flowControl.js#L21-L29), and there are two proposed ways to try to make this more clear.

One is [here](https://github.com/rmurphey/js-assessment-answers/pull/26), another [is described here](https://github.com/rmurphey/js-assessment-answers/issues/27). At the moment I'm not sure which I prefer, but I figured I'd document both options :)

**Comment by pertrai1** [comment]
@jmeas yes the second link was much easier to understand as that is the way that I have seen it before so was not clear how the previous version was the same. Maybe the test is not supposed to be geared towards a novice programmer, but either way I feel much better with the `===` and `!==` approach.

**Comment by ashleygwilliams** [comment]
the code is definitely supposed to be novice-level. this was a great issue. let us know if you see anything else, @pertrai1 !

**Pull request closed without merging**
