### PR TITLE
Manage browser deps in package, not local libs; remove require as a dep

### PR DESCRIPTION
**Pull request by ashleygwilliams**
- remove local dep files
- add pacakges to package.json
- update runner.js and runner.html to use node_modules/
- update app/config to use node_modules/

solves #106

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
i'm not certain i got everything but `npm start` and `grunt develop` both work the way they previously did. would like to get this in asap so @jmeas can do #108. review?

**Comment by ashleygwilliams** [comment]
hey hey @jmeas ! merge meeee

**Comment by ashleygwilliams** [comment]
this now removes `require` as a dep and fixes #108 and #97. this is a *huge* change, reviews PLEASE. @jmeas @rmurphey @kadamwhite

**Comment by ashleygwilliams** [comment]
also, from what i can tell, solves #75

**Comment by jacobroufa** [comment]
This looks good to me. :+1:

**Comment by jmeas** [comment]
lgtm :+1:

Awesome work here @ashleygwilliams. srsly.

**Comment by ashleygwilliams** [comment]
thxx @jmeas - wanna do the honor of merging? :crown:

**Pull request merged**
