### PR TITLE
Add babeljs for tests, let people use es6

### PR DESCRIPTION
**Pull request by kid-icarus**

### CODE REVIEW

**Comment by jmeas** [comment]
Thanks for the PR, @kid-icarus! If we want to add this, we will also want to add the browser compiler in [the spec runner](https://github.com/rmurphey/js-assessment/blob/master/tests/runner.html). The docs on setting that up are [here](https://babeljs.io/docs/usage/browser/).

So that leaves the question...do we want to support Babel? Note that Babel doesn't just let you *just* run ES6. It lets folks run [any ECMAScript proposal that's stage2 or beyond (by default)](http://babeljs.io/blog/2015/03/31/5.0.0/).

**Comment by kid-icarus** [comment]
I just tried adding in the browser compiler and I ran into some issues but I'll give it another shot after work  :)

**Comment by kid-icarus** [comment]
So I ran into a few issues trying to use the browser.js in babel-core. I included the script and then used the type="text/babel" on the test answer scripts.

For each of the test answers scripts, in console I'm seeing `Uncaught ReferenceError: exports is not defined` and the assertions fail with errors like: `ReferenceError: arraysAnswers is not defined`. I'm not sure if using the type="text/babel" transform/run combo is doing something wrong or if I'm missing something.

I thought the babel transform might be adding 'use strict' at the top so I just tried just hardcoding window.* for both the answers object and inside the test assertion and even then I was seeing window.arraysAnswers = { ... as undefined from within the assertion. If someone could has any more insight on that I'd love to hear it.

Another route we could go would be to use grunt-babel to do the compilation, but then that requires users to use grunt instead of it being an optional thing. Maybe there's some type of conditional templating we could use with grunt that would allow non-grunt users to just be limited to not using babel?

Feedback appreciated :)

**Comment by jmeas** [comment]
@kid-icarus, I'd prob. hold off on any further work until we decide that this is the direction we want to go. W. that said, if you're curious, it may have something to do with [the default value of the `modules` option](https://babeljs.io/docs/usage/options/). I haven't yet used the browser transpiler, so I'm not sure if it's even possible to change that config. If not, we may need to do some refactoring to make all of the pieces work together.

In any event, it could be a few hrs of work, and there hasn't been any consensus on whether we want this feature or not, so it's probably safest to wait :)

**Comment by ashleygwilliams** [comment]
Hi @kid-icarus! This effort is really great, but at the moment, I don't think we want to/can support ES6. Babel would add quite a few levels of complexity, and would additionally require that we rework the answers repository as well. ES6 adds a *lot* of abstractions that I, personally, think are very confusing to beginners. A key audience we'd like to maintain is beginners, so ES6-ifying the answers could be damaging.

In the long run I do think we will support ES6, but at the moment it's not the right decision for us.

**Comment by kid-icarus** [comment]
Sounds good, thanks for the feedback :+1:

**Pull request closed without merging**
