### PR TITLE
use a var statement for every variable declaration

### PR DESCRIPTION
**Pull request by ashleygwilliams**
solves #100 
review @jmeas @kadamwhite ?

### CODE REVIEW

**Comment by jmeas** [comment]
This looks good to me. I ran through the source to see if there were any stragglers, and I found [one place](https://github.com/rmurphey/js-assessment/blob/master/tests/app/functions.js#L66-L69).

Update those and we're good for merge, I think!

**Comment by ashleygwilliams** [comment]
:+1: donezo, @jmeas. merging.

**Comment by jmeas** [comment]
:dancers: :tada: :cake:

**Comment by kadamwhite** [comment]
:balloon: !

**Pull request merged**
